services:
  - type: web
    name: clamaco-backend
    runtime: node
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: USERS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: WEBHOOK_OBRAS
        sync: false
      - key: WEBHOOK_COMERCIAL
        sync: false
      - key: WEBHOOK_FINANZAS
        sync: false
      - key: WEBHOOK_CX
        sync: false
      - key: OPENAI_API_KEY
        sync: false
